finishline:
  location: world, -303.275, 77.200, -60.437
  lines:
  - '&b&lFinish &d&lLine'
start:
  location: world, -303.640, 77.263, 415.690
  lines:
  - '&8&lS&f&lt&8&la&f&lr&8&lt'
results:
  location: world, -303.422, 79.299, 418.699
  lines:
  - '&5&lTime`s'
powers:
  location: survival, -214.490, 108.200, -107.567
  lines:
  - '&0&lP&4&lo&8&lw&c&le&l&0&lr&4&ls'
abc:
  location: survival, -203.417, 108.200, -112.148
  lines:
  - '&b&lABC'
def:
  location: survival, -175.478, 108.200, -112.011
  lines:
  - '&b&lDEF'
ghi:
  location: survival, -147.288, 108.200, -111.965
  lines:
  - '&b&lGHI'
jkl:
  location: survival, -119.327, 108.200, -111.920
  lines:
  - '&b&lJKL'
mno:
  location: survival, -91.202, 108.200, -111.874
  lines:
  - '&b&lMNO'
